/** The complete Material Symbols Rounded vocabulary the UI is allowed to use.
 *
 *  Two reasons this list is explicit rather than "whatever string you pass":
 *  the icon font is subsetted down to exactly these ligatures by
 *  `scripts/subset-icon-font.mjs` (the full variable font is 5 MB, the subset is a few
 *  tens of kB), and a closed set stops the same concept picking up three different
 *  glyphs across panels. Adding an icon means adding it here and re-running
 *  `npm run icons`.
 */
export const ICON_NAMES = [
  // Shell chrome
  "menu",
  "close",
  "search",
  "my_location",
  "location_searching",
  "layers",
  "map",
  "settings",
  "tune",
  "more_horiz",
  "more_vert",
  "arrow_back",
  "arrow_forward",
  "arrow_upward",
  "arrow_downward",
  "chevron_left",
  "chevron_right",
  "expand_more",
  "expand_less",
  "unfold_more",
  "drag_handle",
  "drag_indicator",
  "open_in_new",
  "open_in_full",
  "close_fullscreen",
  "fullscreen",
  "add",
  "remove",
  "check",
  "done_all",
  "clear",
  "refresh",
  "sync",
  "undo",
  "redo",
  "delete",
  "edit",
  "content_copy",
  "share",
  "save",
  "link",
  "download",
  "upload",
  "filter_list",
  "sort",
  "visibility",
  "visibility_off",
  "lock",
  "lock_open",
  "info",
  "help",
  "warning",
  "error",
  "check_circle",
  "cancel",
  "light_mode",
  "dark_mode",
  "keyboard_arrow_down",
  "keyboard_arrow_up",
  "keyboard_return",
  "history",
  "star",
  "star_border",
  "favorite",
  "favorite_border",
  "bookmark",
  "bookmark_border",
  "push_pin",
  "flag",
  "label",

  // Modes
  "person_pin_circle",
  "explore",
  "route",
  "stadia_controller",
  "forum",
  "person",

  // Places and navigation
  "place",
  "add_location",
  "pin_drop",
  "near_me",
  "directions",
  "directions_car",
  "directions_bike",
  "directions_walk",
  "directions_bus",
  "directions_boat",
  "two_wheeler",
  "local_shipping",
  "rv_hookup",
  "flight",
  "train",
  "hiking",
  "downhill_skiing",
  "kayaking",
  "swap_vert",
  "swap_horiz",
  "alt_route",
  "fork_right",
  "trip_origin",
  "outlined_flag",
  "straighten",
  "timer",
  "schedule",
  "calendar_month",
  "date_range",
  "event",
  "today",

  // Layers and data domains
  "terrain",
  "forest",
  "park",
  "water_drop",
  "waves",
  "landscape",
  "volcano",
  "public",
  "satellite_alt",
  "grid_on",
  "bar_chart",
  "show_chart",
  "photo_camera",
  "photo_library",
  "image",
  "image_not_supported",
  "restaurant",
  "local_cafe",
  "local_bar",
  "sports_bar",
  "storefront",
  "hotel",
  "cabin",
  "local_parking",
  "ev_station",
  "local_gas_station",
  "wc",
  "shower",
  "museum",
  "castle",
  "church",
  "theater_comedy",
  "attractions",
  "location_city",
  "airport_shuttle",
  "sports_soccer",
  "sports_gymnastics",
  "skateboarding",
  "pool",
  "fitness_center",
  "sailing",
  "cottage",
  "night_shelter",
  "water_full",
  "medical_services",
  "school",
  "account_balance",
  "apartment",
  "electric_bolt",
  "cell_tower",
  "traffic",
  "construction",
  "shield",
  "eco",
  "pets",
  "science",

  // Weather
  "wb_sunny",
  "cloud",
  "rainy",
  "snowing",
  "thunderstorm",
  "air",
  "thermostat",
  "umbrella",
  "foggy",
  "storm",
  "radar",
  "compress",
  "humidity_percentage",
  "water",

  // AI, guide and social
  "auto_awesome",
  "smart_toy",
  "chat_bubble",
  "send",
  "mic",
  "menu_book",
  "description",
  "article",
  "translate",
  "campaign",
  "group",
  "person_add",
  "how_to_reg",
  "verified",
  "workspace_premium",
  "payments",
  "account_balance_wallet",
  "toll",
  "volunteer_activism",

  // Game
  "casino",
  "military_tech",
  "emoji_events",
  "bolt",
  "diamond",
  "inventory_2",
  "swords",
  "shield_moon",
  "explore_nearby",
  "3d_rotation",
  "view_in_ar",

  // Status and feedback
  "progress_activity",
  "hourglass_empty",
  "cloud_off",
  "wifi_off",
  "signal_cellular_alt",
  "battery_alert",
  "notifications",
  "notifications_off"
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Set form, used by the subset script and by the dev-only guard in `Icon`. */
export const ICON_NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);
